### PR TITLE
fix: update frontend-build and frontend-platform

### PR DESCRIPTION
**Pull request by morenol**
Update frontend-build in order to allow the capability to change the webpack.output.publicPath from environment variables.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-5072](https://openedx.atlassian.net/browse/OSPR-5072) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@morenol Thank you for your contribution, is this Blended work?

**Comment by natabene** [comment]
@morenol I am lining this up for our review.

**Comment by felipemontoya** [comment]
I did a complete test with all the necessary PRs using the native install and left all the instructions in https://discuss.openedx.org/t/deploying-mfes-in-the-community/2868/22.

If this test is acceptable we can approve and merge this so that it makes the cut of Koa next monday (Nov 9).

**Comment by felipemontoya** [comment]
Hey @davidjoy,

we are trying to finish this MFEs for the community feature before we create the Koa master branches and I'd like to ask your help here.
This PR, updates frontend-build and frontend-platform so that it includes the changes that allow operators to set the `PUBLIC_PATH` (relevant PRs https://github.com/edx/frontend-platform/pull/113 and https://github.com/edx/frontend-build/pull/119). By default this variable is empty so it will not affect the production configurations for edx.

We are in the process of testing the complete feature, but the critical part of the discussion actually lies on the configuration repo bits. The complexity would be greatly reduced if we merge this. If you think this can be safely merged, please do so.

I'm no core-contributor for this repo, but I have tested this and I approve this changes.

cc: @nedbat

**Review by felipemontoya — APPROVED** [review]

**Review by davidjoy — APPROVED** [review]

**Comment by edx-webhook** [comment]
@morenol 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-profile&entry.867055334=https://github.com/edx/frontend-app-profile/pull/386&entry.1484655318=https://github.com/morenol&entry.752974735=2020-10-20+21:57&entry.1917517419=2020-11-10+21:31&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
