### PR TITLE
Hide 'View My Records' button if no credentials service.

### PR DESCRIPTION
**Pull request by mtyaka**
This hides the "View My Records" button from users profile page if `CREDENTIALS_BASE_URL` is not configured.

**Sandbox**: https://mfeplayground-master.opencraft.hosting/

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-5817](https://openedx.atlassian.net/browse/OSPR-5817) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@mtyaka Thank you for your contribution. Please let me know once it is ready for our review.

**Review by davidjoy — APPROVED** [review]

**Comment by davidjoy** [comment]
This makes sense to me - I'm assuming it was ready for review, but if not, let me know and I can take another look. :)

**Comment by mtyaka** [comment]
Thanks for looking at this @davidjoy! I was waiting for [my sandbox](https://mfeplayground-master.opencraft.hosting) to build before marking this ready for review.

It built successfully, so if you can go ahead and merge this that would be great :)

**Comment by davidjoy** [comment]
Hmm, how do I log into that sandbox?  The usual devstack accounts don't seem to work. :) Just wanted to give it a spin.

**Comment by mtyaka** [comment]
@davidjoy Ah, sorry, I didn't create that sandbox with the standard devstack accounts. I added an account for staff@example.com now, but I also realized that in the meantime I already reused that sandbox for https://github.com/edx/configuration/pull/6438, where I set the `CREDENTIALS_BASE_URL` to a non-empty string.

I have another sandbox running a branch based on lilac.master with the commit from this PR cherry-picked into it: https://mfeplayground.opencraft.hosting - you can check it out using the staff@example.com account.

If you want I can also rebuild the master sandbox with `CREDENTIALS_BASE_URL` set to an empty string.

**Comment by edx-webhook** [comment]
@mtyaka 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-profile&entry.867055334=https://github.com/edx/frontend-app-profile/pull/421&entry.1484655318=https://github.com/mtyaka&entry.752974735=2021-05-31+07:40&entry.1917517419=2021-06-04+16:22&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by davidjoy** [comment]
Thanks for that - looks good.  Merged!

**Pull request merged**
